version: "3"

services:
  mysql:
    image: percona:5.5
    ports:
      - "127.0.0.1:3308:3306/tcp"
    volumes:
      - ./resources/local-dump.sql:/docker-entrypoint-initdb.d/local-dump.sql:ro
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
    networks:
      - tier

  app:
    image: macpaw_test:latest
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    volumes:
      - './:/app'
    ports:
      - '81:80'
    networks:
      - tier

networks:
  tier:
    external:
      name: macpaw_test

volumes:
  mysql:
    driver: local